### ISSUE TITLE
Not an Issue - This Module Rocks!

### ISSUE THREAD

**Issue by trebleCode** [brianbunke/ArrayList#1]
### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

> ```posh
> (Get-Module ArrayList -ListAvailable).Version
> $PSVersionTable
> ```

Just read your article and tried this out. Abstraction is king with PowerShell! Great work Brian

**Comment by brianbunke** [comment]
Hey, this is really nice of you. I appreciate it!
